services:
  server:
    image: 'nginx:stable-alpine' # using stable-alpine version
    ports:
      - '8000:80' # containers local port 80 is exposed to outside port 8000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # mounting custom config to the images config location to override default config
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
  artisan:
  npm: